/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.fmod.jni;

public class FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        FMODJNI.delete_FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean equals(Object obj) {
  	if(obj == this) return true;
  	if(obj == null) return false;
  	if (! (obj instanceof FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES)) return false;
    return this.swigCPtr == ((FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES)obj).swigCPtr;
  }
  public int hashCode() {
     return (int)swigCPtr;
  }

  public void setEventid(FMOD_GUID value) {
    FMODJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_eventid_set(swigCPtr, this, FMOD_GUID.getCPtr(value), value);
  }

  public FMOD_GUID getEventid() {
    long cPtr = FMODJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_eventid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_GUID(cPtr, false);
  }

  public void setProperties(FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES value) {
    FMODJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_properties_set(swigCPtr, this, FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES.getCPtr(value), value);
  }

  public FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES getProperties() {
    long cPtr = FMODJNI.FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES_properties_get(swigCPtr, this);
    return (cPtr == 0) ? null : new FMOD_STUDIO_TIMELINE_BEAT_PROPERTIES(cPtr, false);
  }

  public FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES() {
    this(FMODJNI.new_FMOD_STUDIO_TIMELINE_NESTED_BEAT_PROPERTIES(), true);
  }

}
